#!/bin/bash

# This is only useful if you have the script path and/or arguments in a 
# single string. Normally it is easier to do something like 
# (cd /some/path; ./run)
# instead of cdrun /some/path/run

CMD=$1
shift
SOURCE_DIR="$( cd "$( dirname $CMD )" && pwd )"
pushd $SOURCE_DIR > /dev/null
./`basename $CMD` $*
popd > /dev/null
